config/routes.rb
Depot::Application.routes.draw do

  get 'admin' => 'admin#index'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'login' => :destroy
  end

  resources :users

  resources :orders

  resources :line_items

  resources :carts

  get "store/index"

  resources :products do
    get :who_bought, :on => :member
  end

  match 'line_items/decrement_quantity/:id' => 'line_items#decrement_quantity'

  root :to => 'store#index', :as => 'store'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pragprog Books Online Store</title>
  <%= stylesheet_link_tag "scaffold" %>
  <%= stylesheet_link_tag "depot", :media => "all" %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body id="store">
  <div id="banner">
    <%= image_tag("logo.png") %>
    <%= @page_title || "Pragmatic Bookshelf" %>
  </div>
  <div id="columns">
    <div id="side">

      <% if @cart %>
        <%= hidden_div_if(@cart.line_items.empty?, :id => "cart") do %>
          <%= render @cart %>
        <% end %>
      <% end %>
      
      <span id="dateTime"><%= DateTime.now %></span>
      <%= link_to 'Home', store_path %><br />
      <a href="http://www..../faq">Questions</a><br />
      <a href="http://www..../news">News</a><br />
      <a href="http://www..../contact">Contact</a><br />

      <% if session[:user_id] %>
        <br />
        <%= link_to 'Orders',   orders_path %><br />
        <%= link_to 'Products', products_path %><br />
        <%= link_to 'Users',    users_path %><br />
        <br />
        <%= button_to 'Logout', login_path, :method => :delete %>
      <% end %>  
    </div>
    <div id="main">
      <%= yield %>
    </div>
  </div>
</body>
</html>